plugin:
  id: "dna-frame-translation"
  name: "DNA/RNA Frame Translation"
  description: "Translates DNA/RNA sequences to amino acid sequences using 3-frame or 6-frame translation. Supports custom start/stop codons or translation from position 0. Useful for proteogenomics, novel peptide discovery, and alternative splicing analysis."
  version: "1.0.0"
  author: "Toan Phung"
  category: "proteomics"
  subcategory: "sequence-analysis"
  icon: "biotech"
  repository: "https://github.com/noatgnu/dna-frame-translation-plugin"

runtime:
  environments: ["python"]
  entrypoint: "translation_runner.py"

inputs:
  - name: "input_file"
    label: "Input Sequence File"
    type: "file"
    required: true
    accept: ".fasta,.fa,.fna,.csv,.tsv,.txt"
    description: "File containing DNA/RNA sequences (FASTA or tabular format)"

  - name: "input_format"
    label: "Input Format"
    type: "select"
    required: true
    default: "auto"
    options:
      - value: "auto"
        label: "Auto-detect"
      - value: "fasta"
        label: "FASTA"
      - value: "csv"
        label: "CSV (comma-separated)"
      - value: "tsv"
        label: "TSV (tab-separated)"
    description: "Format of input file. 'auto' detects based on file extension."

  - name: "sequence_column"
    label: "Sequence Column"
    type: "text"
    required: false
    default: "sequence"
    description: "Column name containing sequences (for tabular input)"
    visibleWhen:
      field: "input_format"
      equalsAny: ["csv", "tsv"]

  - name: "id_column"
    label: "ID Column"
    type: "text"
    required: false
    default: "gene"
    description: "Column name for sequence identifiers (for tabular input)"
    visibleWhen:
      field: "input_format"
      equalsAny: ["csv", "tsv"]

  - name: "translation_mode"
    label: "Translation Mode"
    type: "select"
    required: true
    default: "six_frame"
    options:
      - value: "three_frame"
        label: "3-frame (forward only)"
      - value: "six_frame"
        label: "6-frame (forward + reverse complement)"
    description: "Number of reading frames to translate"

  - name: "use_start_codons"
    label: "Require Start Codon"
    type: "boolean"
    required: false
    default: false
    description: "If enabled, translation starts from specified start codons. If disabled, translates from position 0 in each frame."

  - name: "start_codons"
    label: "Start Codons"
    type: "text"
    required: false
    default: "ATG"
    placeholder: "ATG,GTG,CTG,TTG,ACG"
    description: "Comma-separated list of start codons (standard: ATG; alternatives: GTG, CTG, TTG, ACG)"
    visibleWhen:
      field: "use_start_codons"
      equals: true

  - name: "use_stop_codons"
    label: "Stop at Stop Codon"
    type: "boolean"
    required: false
    default: true
    description: "If enabled, translation stops at specified stop codons. If disabled, translates entire frame (stop codons become *)."

  - name: "stop_codons"
    label: "Stop Codons"
    type: "text"
    required: false
    default: "TAA,TAG,TGA"
    placeholder: "TAA,TAG,TGA"
    description: "Comma-separated list of stop codons (standard: TAA, TAG, TGA)"
    visibleWhen:
      field: "use_stop_codons"
      equals: true

  - name: "min_length"
    label: "Minimum Peptide Length"
    type: "number"
    required: false
    default: 0
    min: 0
    max: 10000
    step: 1
    description: "Minimum amino acid length for output sequences (0 = no filter)"

  - name: "max_length"
    label: "Maximum Peptide Length"
    type: "number"
    required: false
    default: 0
    min: 0
    max: 100000
    step: 1
    description: "Maximum amino acid length for output sequences (0 = no limit)"

  - name: "genetic_code"
    label: "Genetic Code Table"
    type: "select"
    required: false
    default: "1"
    options:
      - value: "1"
        label: "1 - Standard"
      - value: "2"
        label: "2 - Vertebrate Mitochondrial"
      - value: "3"
        label: "3 - Yeast Mitochondrial"
      - value: "4"
        label: "4 - Mold/Protozoan/Coelenterate Mito"
      - value: "5"
        label: "5 - Invertebrate Mitochondrial"
      - value: "6"
        label: "6 - Ciliate/Dasycladacean/Hexamita"
      - value: "9"
        label: "9 - Echinoderm/Flatworm Mito"
      - value: "10"
        label: "10 - Euplotid Nuclear"
      - value: "11"
        label: "11 - Bacterial/Archaeal/Plant Plastid"
      - value: "12"
        label: "12 - Alternative Yeast Nuclear"
      - value: "13"
        label: "13 - Ascidian Mitochondrial"
      - value: "14"
        label: "14 - Alternative Flatworm Mito"
      - value: "15"
        label: "15 - Blepharisma Nuclear"
      - value: "16"
        label: "16 - Chlorophycean Mitochondrial"
      - value: "21"
        label: "21 - Trematode Mitochondrial"
      - value: "22"
        label: "22 - Scenedesmus obliquus Mito"
      - value: "23"
        label: "23 - Thraustochytrium Mitochondrial"
      - value: "24"
        label: "24 - Rhabdopleuridae Mitochondrial"
      - value: "25"
        label: "25 - Candidate Division SR1"
      - value: "26"
        label: "26 - Pachysolen tannophilus Nuclear"
      - value: "27"
        label: "27 - Karyorelict Nuclear"
      - value: "28"
        label: "28 - Condylostoma Nuclear"
      - value: "29"
        label: "29 - Mesodinium Nuclear"
      - value: "30"
        label: "30 - Peritrich Nuclear"
      - value: "31"
        label: "31 - Blastocrithidia Nuclear"
      - value: "32"
        label: "32 - Balanophoraceae Plastid"
      - value: "33"
        label: "33 - Cephalodiscidae Mitochondrial"
    description: "NCBI genetic code table for translation"

outputs:
  - name: "translated_sequences"
    path: "translated_sequences.fasta"
    type: "data"
    description: "Translated amino acid sequences in FASTA format"
    format: "fasta"

  - name: "translation_summary"
    path: "translation_summary.tsv"
    type: "data"
    description: "Summary table with sequence IDs, frames, lengths, and ORF positions"
    format: "tsv"

  - name: "translation_report"
    path: "translation_report.txt"
    type: "report"
    description: "Summary statistics of the translation"
    format: "txt"

execution:
  outputDir: "--output_dir"
  argsMapping:
    input_file: "--input_file"
    input_format: "--input_format"
    sequence_column: "--sequence_column"
    id_column: "--id_column"
    translation_mode: "--translation_mode"
    use_start_codons:
      flag: "--use_start_codons"
      when: "true"
    start_codons: "--start_codons"
    use_stop_codons:
      flag: "--use_stop_codons"
      when: "true"
    stop_codons: "--stop_codons"
    min_length: "--min_length"
    max_length: "--max_length"
    genetic_code: "--genetic_code"
  requirements:
    python: ">=3.11"
    pythonRequirementsFile: "requirements.txt"

example:
  enabled: true
  values:
    input_format: "auto"
    translation_mode: "six_frame"
    use_start_codons: false
    start_codons: "ATG,GTG,CTG"
    use_stop_codons: true
    stop_codons: "TAA,TAG,TGA"
    min_length: 20
    max_length: 0
    genetic_code: "1"

diagram:
  enabled: true
